name: CI

on:  [push, pull_request]

jobs:
  eslint:
    name: lint code base
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: install packages
        working-directory: ./
        run: yarn install --frozen-lockfile

      - name: run eslint
        run: yarn test:eslint
